name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Fixed'
    labels:
      - 'fix'
      - 'bug'
      - 'patch'
  - title: 'Added'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Changed'
    labels:
      - 'change'
      - 'chore'
  - title: 'Security'
    label: 'security'
exclude-labels:
  - 'skip-changelog'
  - 'documentation'
change-template: '- $TITLE by @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
      - 'change'
      - 'chore'
  patch:
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'patch'
  default: patch
version-template: '$MAJOR.$MINOR.$PATCH.0'
autolabeler:
  - label: 'chore'
    files:
      - '*.json'
  - label: 'documentation'
    files:
      - '*.md'
include-paths:
  - 'EXAMPLE/**'
  - 'MAIN/**'
  - 'TEST/**'
template: |
  $CHANGES
  ### Deprecated
  <!---for soon-to-be removed features--->
  - 
  ### Removed
  <!---for now removed features--->
  - 
