name-template: 'v$RESOLVED_VERSION.0'
tag-template: 'v$RESOLVED_VERSION.0'
categories:
  - title: 'Fixed'
    labels:
      - '📊 insights'
      - '🐛 bug'
      - '🌳 dependencies'
  - title: 'Added'
    labels:
      - '✨ enhancement'
      - '💡 ideas'
  - title: 'Changed'
    labels:
      - '🚀 major'
      - '⚠️ invalid'
  - title: 'Security'
    label: '🔒 security'
exclude-labels:
  - '🙈 skip-changelog'
  - '📝 documentation'
  - '📞 help wanted'
  - '🤔 question'
  - '😶 wontfix'
change-template: '- $TITLE by @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - '🚀 major'
  minor:
    labels:
      - '✨ enhancement'
      - '💡 ideas'
  patch:
    labels:
      - '📊 insights'
      - '🐛 bug'
      - '🌳 dependencies'
      - '⚠️ invalid'
      - '🔒 security'
  default: patch
autolabeler:
  - label: '🙈 skip-changelog'
    files:
      - '*.json'
  - label: '📝 documentation'
    files:
      - '*.md'
template: |
  $CHANGES
  ## Deprecated

  - 
  ## Removed

  - 
